redis:
  connection_string: <%= ENV['REDIS_CONNECTION_STRING'] %>
rpc_client:
  url: <%= ENV['RPC_HOST'] %>
contracts:
  isbn_registry:
    file_path: <%= Rails.root.join('lib', 'solidity_scripts', 'isbn_registry.sol') %>
    address: '<%= ENV['ISBN_REGISTRY_ADDRESS'] %>'
  book_instance_registry:
    file_path: <%= Rails.root.join('lib', 'solidity_scripts', 'book_instance_registry.sol') %>
    address: '<%= ENV['BOOK_INSTANCE_REGISTRY_ADDRESS'] %>'
